# -*- coding: utf-8 -*-
"""file writer, updated cv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b1S3khRD6WimdrO4TcQAJVSTxDZGekkz
"""

import sys
import exhibition_2

sys.run('updated_data.csv' < 'data.csv')
file=sys.argv[1]
with open(file) as f:
  csv=f.readlines()

with open('updated_data.csv','a') as f:
    for i in csv:
      f.write(i)

if len(csv)>=50:
  exhibition_2.algo()